In [2]:
import numpy as np
import math

In [6]:
# creating Query, Key, Value
L, d_K, d_V = 4, 8, 8
q = np.random.randn(L, d_K)
k = np.random.randn(L, d_K)
v = np.random.randn(L, d_V) 
print(q,k,v, sep="\n-------------------------------------------\n")

[[-1.52268931 -1.4782581  -0.03439015 -1.95761889 -0.26820739  0.59758285
   0.13767827  0.37600382]
 [-0.62291954  0.43579031 -1.33992322  0.22032349 -0.11711665  0.95108453
   0.26710959  1.98511966]
 [ 0.16387946 -0.047156   -1.5429586   0.07287787  1.46454299  1.12197514
  -0.07419645 -0.23087365]
 [-1.67441113  1.32634428 -1.26751411  1.71596718  0.5725955  -0.08130886
  -0.02004459 -0.48953263]]
-------------------------------------------
[[-0.52343824 -1.73711874  0.12384902  0.05038051 -1.22395884  1.08990418
   0.45273098  0.23054131]
 [-0.79363833 -0.1607422  -0.89809427  0.40309064  0.15168338 -1.50029654
  -0.37666763  1.02757665]
 [ 0.07639509  0.68486991  0.51118305 -0.01769179 -0.64440864 -0.85676097
   0.90291828  0.07050913]
 [ 0.27640205  0.33491821 -1.47982822 -1.51338878 -0.05814828  1.09844285
   0.25208242  0.70455145]]
-------------------------------------------
[[-0.89674785 -0.63452837 -1.86045605 -1.38436558 -0.01571999 -0.76083829
  -1.33394303  1.15265836]
 

In [8]:
# what is selfattention fomula
# selfattention = softmax(q*k.T/sqrt(d_K) + M)v
# for decreasing the variance of attention
scale = np.matmul(q, k.T)/ math.sqrt(d_K)

In [14]:
# masking : this is to ensure words don't get context from words generated in the future and decorder need it
mask = np.tril(np.ones((L,L)))
mask

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

In [15]:
mask[mask==0] = -np.infty
mask[mask==1] = 0
mask

array([[  0., -inf, -inf, -inf],
       [  0.,   0., -inf, -inf],
       [  0.,   0.,   0., -inf],
       [  0.,   0.,   0.,   0.]])

In [18]:
scale + mask

array([[ 1.55233172,        -inf,        -inf,        -inf],
       [ 0.41461562,  0.78173775,        -inf,        -inf],
       [-0.29974235, -0.13358094, -0.9892779 ,        -inf],
       [-0.85187991,  0.94012438, -0.08830778, -0.42864053]])

In [20]:
# Softmax 
# softmax formula is e^xi/ sum(e^xj)
def softmax(x):
    return (np.exp(x).T) / (np.sum(np.exp(x), axis=-1)).T

In [22]:
attention = softmax(scale + mask)
new_v = np.matmul(attention, v)
new_v

array([[-1.07051535, -0.36420375, -0.61206494, -1.84951622, -0.72497137,
        -0.45821618, -1.65583438,  1.26919379],
       [-0.24756664, -0.30683886,  1.92526485, -1.40176069, -0.88397546,
         0.91392933, -0.26824001, -0.00522564],
       [-0.04212323, -0.28047744,  0.26863182, -0.47876599, -0.42526455,
         0.11234896,  0.03159739, -0.0565286 ],
       [-0.00504725, -0.22680441,  0.07089514, -0.26363678, -0.0222623 ,
         0.14401908,  0.05723614, -0.05456927]])

In [24]:
v

array([[-0.89674785, -0.63452837, -1.86045605, -1.38436558, -0.01571999,
        -0.76083829, -1.33394303,  1.15265836],
       [-0.24595801,  0.83713414,  2.11415451, -0.1876077 ,  0.22100072,
         0.94753697, -0.64032009,  0.27390428],
       [-0.18726216,  0.20462088,  0.90341253, -0.5786664 , -2.10612244,
        -0.48143045, -0.2611059 ,  0.10779216],
       [-0.03528443, -1.58555111,  0.49561588, -1.84304   , -0.15563197,
         1.00681295,  0.40012817, -0.38148453]])

In [ ]:
def selfattention(query, key, value, mask_val=None):
    scale = np.matmul(query * key.T) / math.sqrt(d_K)
    if mask_val != None:
        mask = np.tril(np.ones((L,L)))
        mask[mask==0] = -np.infty
        mask[mask==1] = 0
        attention = softmax(scale + mask)
        new_v = np.matmul(attention, value)
        return new_v
    
    attention = softmax(scale)
    new_v = np.matmul(attention, value)
    return new_v